name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Provide the path to the upstream merge script'
        default: 'scripts/dev/upstream_merge/upstream_merge_and_test.py'
        required: true
        type: string

jobs:
  test_run_a_python_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}   # Ensures the correct branch (e.g., automation2) is used
    
    - name: List git config
      run: git config --list
    
    - name: set git pull
      run: git config pull.rebase false

    - name: Run Python upstream merge script
      run: python3 ${{ inputs.filename }}
