# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      filename:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Provide the path to the debug script'
        # Default value if no value is explicitly provided
        default: 'scripts/dev/upstream_merge/debug.py'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_run_a_python_script:
    runs-on: ubuntu-latest
    steps:
    - name: Print working directory
      run: pwd
    
    - name: list sub-directories
      run: ls
      
    - name: Run Python debug script
      run: python3 ${{ inputs.filename }}
