name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Provide the path to the upstream merge script'
        default: 'scripts/dev/upstream_merge/upstream_merge_and_test.py'
        required: true
        type: string

      workItemID:
        description: 'Provide Work Item ID for the upstream merge script'
        default: None
        required: true
        type: string

jobs:
  Run_upstream_merge_and_test_script:
    runs-on: self-hosted
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}   
        submodules: recursive
      
    - name: set git pull
      run: git config pull.rebase false
  
    - name: Run Python upstream merge script
      run: python3 ${{ inputs.filename }} -w ${{ inputs.workItemID }}
